---
- name: 201.10. CREATE TEMPORARY DIRECTORY
  delegate_to: localhost
  ansible.builtin.file:
    dest: "{{ output_directory.results }}/{{ execution_timestamp }}"
    state: directory
    recurse: True

- name: 201.20. COLLECT CONFIG
  ansible.netcommon.netconf_get:
    display: native
    filter: "{{ lookup('template', 'check_{{ template_prefix }}.j2') }}"
    lock: never
  register: output_info

- name: 201.30. SAVING CONFIG
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ output_info.output | to_nice_json }}"
    dest: "{{ output_directory.results }}/{{ execution_timestamp }}/{{ inventory_hostname }}_data_{{ template_prefix }}.json"
...