---
- name: CONFIGURATION OF 6WIND ROUTER
  hosts: device_roles_dci
  gather_facts: no
  connection: ansible.netcommon.netconf

  vars:
    ansible_user: "{{ lookup('env', 'NETWORK_DEVICE_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'NETWORK_DEVICE_PASSWORD') }}"

  roles:
    - role: poll_yang
      tags: poll_yang

...