---
- name: CONFIGURATION OF 6WIND ROUTER
  hosts: device_roles_dci
  connection: ansible.netcommon.netconf

  vars:
    ansible_user: "{{ lookup('env', 'NETWORK_DEVICE_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'NETWORK_DEVICE_PASSWORD') }}"
    ## Used for execution
    execution_timestamp: "{{ ansible_date_time.iso8601_basic }}"
    
  roles:
    - role: 200_poll_yang_modules
      tags: yang

    - role: 201_poll_data
      vars:
        template_prefix: state
      tags: state

    - role: 201_poll_data
      vars:
        template_prefix: config
      tags: config

...