---
- name: CONFIGURATION OF 6WIND ROUTER
  hosts: device_roles_dci
  connection: ansible.netcommon.netconf

  vars:
    ## Connectivity data
    ansible_user: "{{ lookup('env', 'NETWORK_DEVICE_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'NETWORK_DEVICE_PASSWORD') }}"
    ## Used for execution
    execution_timestamp: "{{ ansible_date_time.iso8601_basic }}"
    target_vrf: DUMMY_VRF

  roles:
    - role: collect_netbox
      tags: 
        - push_base
        - push_vrf

    - role: push_base
      tags: push_base

    - role: push_vrf
      tags: push_vrf
...