---
- name: CONFIGURATION OF 6WIND ROUTER
  hosts: device_roles_dci
  connection: ansible.netcommon.netconf

  vars:
    ## Connectivity data
    ansible_user: "{{ lookup('env', 'NETWORK_DEVICE_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'NETWORK_DEVICE_PASSWORD') }}"
    ## Used for execution
    execution_timestamp: "{{ ansible_date_time.iso8601_basic }}"
    target_vrf: DUMMY_VRF

  roles:
    - role: 100_collect_netbox
      tags: 
        - infrastructure
        - customer

    - role: 300_prepare_vars
      tags: 
        - infrastructure
        - customer

    - role: 301_push_config
      vars:
        template_prefix: main
      tags: infrastructure

    - role: 301_push_config
      vars:
        template_prefix: non_main
      tags: customer
...