---
######################################
#   POLLING EXTRA DATA FROM NETBOX   #
######################################
- name: 10. POLL SITE DATA
  ansible.builtin.uri:
    url: "{{ lookup('env', 'NETBOX_BASE_URL') }}/api/dcim/sites/?id={{ nb_site_id }}"
    method: GET
    return_content: yes
    headers:
      Authorization: Token {{ lookup('env', 'NETBOX_TOKEN') }}
  register: netbox_site_data

- name: 20. POLL VRFS DATA
  ansible.builtin.uri:
    url: "{{ lookup('env', 'NETBOX_BASE_URL') }}/api/ipam/vrfs/?limit=65535"
    method: GET
    return_content: yes
    headers:
      Authorization: Token {{ lookup('env', 'NETBOX_TOKEN') }}
  register: netbox_vrfs_data

######################################
#    COLLECTING PRE CHANGE CONFIG    #
######################################
- name: 30. PRE-CHANGE // CREATE TEMPORARY DIRECTORY
  delegate_to: localhost
  ansible.builtin.file:
    dest: "{{ output_directory.ops }}/{{ execution_timestamp }}"
    state: directory
    recurse: True

- name: 40. PRE-CHANGE // COLLECT CONFIG OF VRF {{ target_vrf}}
  ansible.netcommon.netconf_get:
    display: native
    filter: 
      config:
        "@xmlns": "urn:6wind:vrouter"
        vrf:
          name: "{{ target_vrf }}"
    lock: never
  register: vrf_config_pre_change

- name: 50. PRE-CHANGE // SAVING CONFIG
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ vrf_config_pre_change.output | to_nice_json }}"
    dest: "{{ output_directory.ops }}/{{ execution_timestamp }}/{{ inventory_hostname }}_pre.json"

######################################
#      PERFORMING CHANGE CONFIG      #
######################################
- name: 60. CHANGE // PREPARE NETCONF MESSAGE BODY
  delegate_to: localhost
  ansible.builtin.template:
    src: vrf.j2
    dest: "{{ output_directory.ops }}/{{ execution_timestamp }}/{{ inventory_hostname }}_change.json"

- name: 70. CHANGE // APPLY CONFIGURATION
  ansible.netcommon.netconf_config:
    format: json
    content: "{{ lookup('template', 'vrf.j2') }}"

######################################
#    COLLECTING POST CHANGE CONFIG   #
######################################
- name: 80. POST-CHANGE // COLLECT CONFIG OF VRF {{ target_vrf}}
  ansible.netcommon.netconf_get:
    display: native
    filter: 
      config:
        "@xmlns": "urn:6wind:vrouter"
        vrf:
          name: "{{ target_vrf }}"
    lock: never
  register: vrf_config_post_change

- name: 90. POST-CHANGE // SAVING CONFIG
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ vrf_config_post_change.output | to_nice_json }}"
    dest: "{{ output_directory.ops }}/{{ execution_timestamp }}/{{ inventory_hostname }}_post.json"

######################################
#    COMPARING PRE AND POST CHANGE   #
######################################
- name: 100. COMPARING PRE AND POST CHANGE
  delegate_to: localhost
  ansible.utils.fact_diff:
    before: "{{ vrf_config_pre_change.output | ansible.utils.to_paths }}"
    after: "{{ vrf_config_post_change.output | ansible.utils.to_paths }}"
  register: vrf_config_diff

- name: 110. SAVING DIFF
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ vrf_config_diff | to_nice_json }}"
    dest: "{{ output_directory.ops }}/{{ execution_timestamp }}/{{ inventory_hostname }}_diff.json"
...